services:
  backend:
    image: "efrei2023/backend-alexah:2001"
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - efrei_net

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: "efrei2023/frontend-alexah:2001"
    container_name: frontend
    networks:
      - efrei_net
    ports:
      - "8081:80"
    depends_on:
      - backend
    
networks:
  efrei_net:
    driver: bridge
