alertmanager:
  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'projectdevops252@gmail.com'
      smtp_auth_username: 'projectdevops252@gmail.com'
      smtp_auth_password: 'cqhn wpqr bmzo pqun'
      smtp_require_tls: true

    route:
      receiver: 'email-alert'

    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'lazhar.hamel@efrei.fr'
          - to: 'alex6faure@gmail.com'