apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: efrei2023/project-alexah:2001
        ports:
        - containerPort: 8081  # Modifié pour correspondre au port exposé dans le Dockerfile
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /  # Ajustez ce chemin selon votre endpoint de santé
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /  # Ajustez ce chemin selon votre endpoint de santé
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10