config:
  clients:
    - url: http://loki-gateway.prod.svc.cluster.local/loki/api/v1/push
      tenant_id: "default" # Replace "default" with the desired OrgID
  positions:
    filename: /run/promtail/positions.yaml
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
