config:
  clients:
    - url: http://loki.prod.svc.cluster.local/loki/api/v1/push
  positions:
    filename: /tmp/positions.yaml
  scrape_configs:
    - job_name: system
      static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log
