serverFiles:
  alerting_rules.yml:
    groups:
      - name: Instances
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              description: "This is a message of alert manager from Team 9, I think you should give us a 20/20 on the project :)"
              summary: "Alexis FAURE, Noah ATTIA, Elisa CHAZARD, Guillaume CLAVIER"