apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
  - name: http
    port: 8080      # Port du service
    targetPort: 8080
    nodePort: 30081  # Port du container
    protocol: TCP