apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
  - port: 8081        # Port du service
    targetPort: 8081  # Port du container
    protocol: TCP